apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: muqh13wiu-nodejs
  janus-idp.io/tekton: muqh13wiu-nodejs
  backstage.io/kubernetes-id: muqh13wiu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: muqh13wiu-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
